movieproject/movieapp/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'
urlpatterns = [
    path("", views.index, name='index'),
    path("movie/<int:movie_id>/", views.detail, name='detail'),
    path("add/", views.add_movie, name='add_movie'),
    path("update/<int:id>/",views.update, name='update'),
    path("delete/<int:id>/",views.delete, name='delete'),
]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self) :
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','year','img']

movieproject/movieapp/views.py
from django.shortcuts import redirect, render
from . models import Movie
from .forms import MovieForm

# Create your views here.
def index(req):
    movie = Movie.objects.all()
    context = {
        'movie_list' : movie
    }
    return render (req,"index.html", context)

def detail(req,movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(req,"detail.html",{'i':movie})

def add_movie(req):
    if req.method == "POST":
        name = req.POST.get('name')
        desc = req.POST.get('desc')
        year = req.POST.get('year')
        img = req.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
        return redirect('/')
    return render(req,"add.html")

def update(req,id):
    movie = Movie.objects.get(id=id)
    form = MovieForm( req.POST or None , req.FILES, instance = movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    else:
        return render(req, "edit.html", {'form':form, 'movie':movie })
    

def delete(req,id):
    if req.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(req, 'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}

{% block body %}

<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Your Movie Name"><br>
    <input type="text" name="desc" placeholder="Enter Your Movie Plot"><br>
    <input type="text" name="year" placeholder="Enter Your Movie Year"><br>
    <input type="file" name="img" ><br>
    <input type="submit" value="Add">
</form>

{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <!-- Image and text -->
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
            Online Movie Store
        </a>
        <a class="btn btn-warning" href="{% url 'movieapp:add_movie' %}">Add</a>

  </nav>
  {% block body %}
  {% endblock %}
</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}

{% block body %}

<form method="post" >
    {% csrf_token %}
    <p>Are you want to delete this movie</p>
    <input class="btn btn-warning" type="submit" value="Yes">
</form>

{% endblock %}

movieproject/templates/detail.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{i.img.url}}" alt="image" width="400px">
        </div>
        <div class="col-md-6">
            <h1>{{i.name}} ({{i.year}})</h1>
            <h6>{{i.desc}}</h6>
            <a class="btn btn-warning" href="{% url 'movieapp:update' i.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' i.id %}">Delete</a>
        </div>
    </div>
</div>


{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}

{% block body %}
<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-warning" type="submit">
</form>

{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" >
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" style=" height: 250px; object-fit: cover;">
                <div class="card-body">
                <h5 class="card-title">{{i.name}}</h5>
                <!-- <p class="card-text">{{i.desc}}</p> -->
                <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">For more details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}